### ISSUE TITLE
Bug: Getting sitter profile error

### ISSUE THREAD

**Issue by xia0m** [hatchways/team-cosmic-crisp#77]
![CleanShot 2021-06-04 at 00 10 20](https://user-images.githubusercontent.com/6465981/120760912-82641600-c4c9-11eb-9dff-838a2c06b268.png)

- here the 'undefined' is a string, it should be undefined, without the quotation mark
-  city==='undefined', date==='undefined' will never be true.

**Comment by gursharan4312** [comment]
We are getting city and date via query parameters which is string so undefined as passed as string by frontend.
